/**
 * Crop Varieties
 * Lists of crops and their varieties for farm creation
 */

export const CROPS = [
  'Grapes',
  'Mango',
  'Pomegranate',
  'Citrus',
  'Banana',
  'Tomato',
  'Sugarcane',
  'Guava',
  'Apple',
  'Pear',
  'Peach',
  'Plum',
  'Cherry',
  'Strawberry',
  'Blueberry',
  'Raspberry',
  'Blackberry',
  'Papaya',
  'Pineapple',
  'Coconut',
  'Arecanut',
  'Cashew',
  'Coffee',
  'Tea',
  'Cocoa',
  'Cotton',
  'Rice',
  'Wheat',
  'Maize',
  'Soybean',
  'Groundnut',
  'Chili',
  'Onion',
  'Potato',
  'Other',
] as const;

export type CropType = (typeof CROPS)[number];

export const CROP_VARIETIES: Record<CropType, string[]> = {
  Grapes: [
    'Thompson Seedless',
    'Flame Seedless',
    'Red Globe',
    'Crimson Seedless',
    'Autumn Crisp',
    'Cotton Candy',
    'Autumn Royal',
    'Moon Drops',
    'Superior Seedless (Sugraone)',
    'Princess Seedless',
    'Sable Seedless',
    'Perlette',
    'Cardinal',
    'Emperor',
    'Italia (Muscat of Alexandria)',
    'Black Corinth (Zante Currant)',
    'Delight',
    'Victoria',
    'Kyoho',
    'Shine Muscat',
    'Ruby Roman',
    'Concord',
    'Niagara',
    'Waltham Cross',
    'Autumn King',
    'Scarlotta Seedless',
    // Wine varieties
    'Cabernet Sauvignon',
    'Merlot',
    'Chardonnay',
    'Sauvignon Blanc',
    'Pinot Noir',
    'Syrah (Shiraz)',
    'Tempranillo',
    'Sangiovese',
    'Malbec',
    'Grenache (Garnacha)',
    'Mourvedre (Monastrell)',
    'Zinfandel (Primitivo)',
    'Pinot Grigio (Pinot Gris)',
    'Riesling',
    'Chenin Blanc',
    'Viognier',
    'Semillon',
    'Gewurztraminer',
    'Moscato (Muscat Blanc)',
    'Nebbiolo',
    'Barbera',
    'Dolcetto',
    "Nero d'Avola",
    'Aglianico',
    'Fiano',
    'Gamay',
    'Tannat',
    'Touriga Nacional',
    'Albarino',
    'Verdejo',
    'Gruner Veltliner',
    'Assyrtiko',
    'Torrontes',
    'Saperavi',
    'Plavac Mali',
    'Xinomavro',
    'Carmenere',
    'Pinotage',
    'Carignan',
    'Cabernet Franc',
    'Petit Verdot',
    'Marsanne',
    'Roussanne',
    'Trebbiano (Ugni Blanc)',
    'Viura (Macabeo)',
    'Rkatsiteli',
    'Feteasca Neagra',
    'Feteasca Alba',
    'Lambrusco',
    'Black Muscat',
    'Arkavati',
    'Bhokri',
    'Petit Sirah (Durif)',
    'Vermentino (Rolle)',
    'Pinot Blanc',
    'Petit Manseng',
    'Gros Manseng',
    'Savagnin',
    'Melon de Bourgogne (Muscadet)',
    'Touriga Franca',
    'Tinta Cao',
    'Baga',
    'Encruzado',
    'Picpoul',
    'Corvina',
    'Rondinella',
    'Molinara',
    'Kadarka',
    'Kekfrankos (Blaufrankisch)',
    'Zweigelt',
    'Blauer Portugieser',
    'St. Laurent',
    'Muller-Thurgau',
    'Mencia',
    'Malagousia',
    'Vidiano',
    'Bonarda',
    'Verdelho',
    'Custom',
  ],
  Mango: [
    'Alphonso',
    'Totapuri',
    'Kesar',
    'Dasheri',
    'Langra',
    'Chausa',
    'Banganapalli',
    'Himsagar',
    'Neelam',
    'Custom',
  ],
  Pomegranate: [
    'Bhagawa',
    'Ganesh',
    'Arakta',
    'Mridula',
    'Ruby',
    'Kandhari',
    'Wonderful',
    'Custom',
  ],
  Citrus: [
    'Nagpur Orange',
    'Kinnow',
    'Mosambi',
    'Lemon',
    'Lime',
    'Grapefruit',
    'Mandarin',
    'Custom',
  ],
  Banana: [
    'Grand Naine',
    'Robusta',
    'Rasthali',
    'Poovan',
    'Nendran',
    'Red Banana',
    'Cavendish',
    'Custom',
  ],
  Tomato: [
    'Roma',
    'Cherry Tomato',
    'Beefsteak',
    'Heirloom',
    'Arka Rakshak',
    'Pusa Rohini',
    'Custom',
  ],
  Sugarcane: ['Co 86032', 'Co 0238', 'Co 98014', 'CoJ 64', 'Co 15023', 'Co 11015', 'Custom'],
  Guava: [
    'Allahabad Safeda',
    'Lalit',
    'Shweta',
    'L-49 (Sardar)',
    'Arka Kiran',
    'Thai Guava',
    'Custom',
  ],
  Apple: ['Red Delicious', 'Royal Gala', 'Fuji', 'Granny Smith', 'Honeycrisp', 'Ambri', 'Custom'],
  Pear: ['Bartlett', 'Bosc', 'Anjou', 'Packham', 'Patharnakh', 'Punjab Beauty', 'Custom'],
  Peach: ['Flordasun', 'Shan-e-Punjab', 'July Elberta', 'Redhaven', 'Pratap', 'Custom'],
  Plum: ['Santa Rosa', 'Satluj Purple', 'Kala Amritsari', 'Frontier', 'Methley', 'Custom'],
  Cherry: ['Bing', 'Rainier', 'Stella', 'Lapins', 'Sweetheart', 'Custom'],
  Strawberry: ['Camarosa', 'Chandler', 'Winter Dawn', 'Sweet Charlie', 'Festival', 'Custom'],
  Blueberry: ['Misty', 'Biloxi', 'Jewel', 'Emerald', 'Sharpblue', 'Custom'],
  Raspberry: ['Heritage', 'Tulameen', 'Autumn Bliss', 'Meeker', 'Custom'],
  Blackberry: ['Arapaho', 'Navaho', 'Triple Crown', 'Chester', 'Custom'],
  Papaya: ['Red Lady', 'Pusa Nanha', 'Pusa Delicious', 'Coorg Honey Dew', 'Arka Surya', 'Custom'],
  Pineapple: ['Kew', 'Queen', 'Mauritius', 'Smooth Cayenne', 'MD-2', 'Custom'],
  Coconut: [
    'West Coast Tall',
    'East Coast Tall',
    'Chowghat Orange Dwarf',
    'Malayan Dwarf',
    'Kalpa Sree',
    'Custom',
  ],
  Arecanut: ['Mangala', 'Sumangala', 'Sreemangala', 'Mohitnagar', 'Kahikuchi', 'Custom'],
  Cashew: ['Vengurla-4', 'Vengurla-7', 'Ullal-1', 'BPP-8', 'Goa-11/6', 'Custom'],
  Coffee: [
    'Arabica - S.795',
    'Arabica - Chandragiri',
    'Arabica - Cauvery',
    'Robusta - CxR',
    'Robusta - Sln.274',
    'Custom',
  ],
  Tea: ['TV-1', 'TV-22', 'UPASI-9', 'UPASI-17', 'TRI-2025', 'Custom'],
  Cocoa: ['Forastero', 'Criollo', 'Trinitario', 'CCRP-6', 'VTLCH-1', 'Custom'],
  Cotton: ['Bt Cotton', 'DCH-32', 'Suvin', 'MCU-5', 'Suraj', 'Custom'],
  Rice: ['Basmati 1121', 'Pusa Basmati 1509', 'IR64', 'Swarna', 'MTU-1010', 'Custom'],
  Wheat: ['HD 2967', 'HD 3086', 'PBW 343', 'Lok-1', 'Sharbati', 'Custom'],
  Maize: ['DHM 117', 'HQPM-1', 'Vivek Hybrid 9', 'PMH-1', 'Pusa HM-4', 'Custom'],
  Soybean: ['JS 335', 'JS 95-60', 'NRC 37', 'MACS 1188', 'RVS 2001-4', 'Custom'],
  Groundnut: ['JL 24', 'GG 20', 'TAG 24', 'Kadiri 6', 'ICGV 91114', 'Custom'],
  Chili: ['Byadagi', 'Guntur Sannam', 'Teja', 'Kashmiri', 'Pusa Jwala', 'Custom'],
  Onion: ['N-53', 'Bhima Red', 'Bhima Dark Red', 'Arka Kalyan', 'Agrifound Light Red', 'Custom'],
  Potato: [
    'Kufri Jyoti',
    'Kufri Pukhraj',
    'Kufri Bahar',
    'Kufri Chipsona-1',
    'Kufri Lima',
    'Custom',
  ],
  Other: ['Custom'],
};

/**
 * Get varieties for a specific crop
 */
export function getVarietiesForCrop(crop: CropType): string[] {
  return CROP_VARIETIES[crop] ?? ['Custom'];
}

/**
 * Check if variety is custom
 */
export function isCustomVariety(variety: string): boolean {
  return variety === 'Custom' || !Object.values(CROP_VARIETIES).flat().includes(variety);
}
