/**
 * Crop Varieties
 * Lists of crops and their varieties for farm creation
 * Ported from iOS AddFarmSheet.swift
 */

export const CROPS = ['Grapes', 'Mango', 'Pomegranate', 'Citrus', 'Banana', 'Other'] as const;

export type CropType = (typeof CROPS)[number];

export const CROP_VARIETIES: Record<CropType, string[]> = {
  Grapes: [
    'Thompson Seedless',
    'Flame Seedless',
    'Red Globe',
    'Crimson Seedless',
    'Autumn Crisp',
    'Cotton Candy',
    'Autumn Royal',
    'Moon Drops',
    'Superior Seedless (Sugraone)',
    'Princess Seedless',
    'Sable Seedless',
    'Perlette',
    'Cardinal',
    'Emperor',
    'Italia (Muscat of Alexandria)',
    'Black Corinth (Zante Currant)',
    'Delight',
    'Victoria',
    'Kyoho',
    'Shine Muscat',
    'Ruby Roman',
    'Concord',
    'Niagara',
    'Waltham Cross',
    'Autumn King',
    'Scarlotta Seedless',
    // Wine varieties
    'Cabernet Sauvignon',
    'Merlot',
    'Chardonnay',
    'Sauvignon Blanc',
    'Pinot Noir',
    'Syrah (Shiraz)',
    'Tempranillo',
    'Sangiovese',
    'Malbec',
    'Grenache (Garnacha)',
    'Mourvedre (Monastrell)',
    'Zinfandel (Primitivo)',
    'Pinot Grigio (Pinot Gris)',
    'Riesling',
    'Chenin Blanc',
    'Viognier',
    'Semillon',
    'Gewurztraminer',
    'Moscato (Muscat Blanc)',
    'Nebbiolo',
    'Barbera',
    'Dolcetto',
    "Nero d'Avola",
    'Aglianico',
    'Fiano',
    'Gamay',
    'Tannat',
    'Touriga Nacional',
    'Albarino',
    'Verdejo',
    'Gruner Veltliner',
    'Assyrtiko',
    'Torrontes',
    'Saperavi',
    'Plavac Mali',
    'Xinomavro',
    'Carmenere',
    'Pinotage',
    'Carignan',
    'Cabernet Franc',
    'Petit Verdot',
    'Marsanne',
    'Roussanne',
    'Trebbiano (Ugni Blanc)',
    'Viura (Macabeo)',
    'Rkatsiteli',
    'Feteasca Neagra',
    'Feteasca Alba',
    'Lambrusco',
    'Black Muscat',
    'Arkavati',
    'Bhokri',
    'Petit Sirah (Durif)',
    'Vermentino (Rolle)',
    'Pinot Blanc',
    'Petit Manseng',
    'Gros Manseng',
    'Savagnin',
    'Melon de Bourgogne (Muscadet)',
    'Touriga Franca',
    'Tinta Cao',
    'Baga',
    'Encruzado',
    'Picpoul',
    'Corvina',
    'Rondinella',
    'Molinara',
    'Kadarka',
    'Kekfrankos (Blaufrankisch)',
    'Zweigelt',
    'Blauer Portugieser',
    'St. Laurent',
    'Muller-Thurgau',
    'Mencia',
    'Malagousia',
    'Vidiano',
    'Bonarda',
    'Verdelho',
    'Custom',
  ],
  Mango: [
    'Alphonso',
    'Totapuri',
    'Kesar',
    'Dasheri',
    'Langra',
    'Chausa',
    'Banganapalli',
    'Himsagar',
    'Custom',
  ],
  Pomegranate: ['Bhagawa', 'Ganesh', 'Arakta', 'Mridula', 'Ruby', 'Kandhari', 'Custom'],
  Citrus: ['Nagpur Orange', 'Kinnow', 'Mosambi', 'Lemon', 'Lime', 'Grapefruit', 'Custom'],
  Banana: [
    'Grand Naine',
    'Robusta',
    'Rasthali',
    'Poovan',
    'Nendran',
    'Red Banana',
    'Cavendish',
    'Custom',
  ],
  Other: ['Custom'],
};

/**
 * Get varieties for a specific crop
 */
export function getVarietiesForCrop(crop: CropType): string[] {
  return CROP_VARIETIES[crop] ?? ['Custom'];
}

/**
 * Check if variety is custom
 */
export function isCustomVariety(variety: string): boolean {
  return variety === 'Custom' || !Object.values(CROP_VARIETIES).flat().includes(variety);
}
