/**
 * Lab test parameter definitions with optimal ranges
 * Based on established agricultural science thresholds for grape farming
 */

export interface ParamOption {
  key: string;
  label: string;
  shortLabel: string;
  unit: string;
  optimalMin: number;
  optimalMax: number;
}

// Soil parameter options with optimal ranges for grape cultivation
export const soilParamOptions: ParamOption[] = [
  {
    key: 'ph',
    label: 'pH',
    shortLabel: 'pH',
    unit: '',
    optimalMin: 6.5,
    optimalMax: 7.5,
  },
  {
    key: 'ec',
    label: 'EC',
    shortLabel: 'EC',
    unit: 'dS/m',
    optimalMin: 0,
    optimalMax: 1.0,
  },
  {
    key: 'organicCarbon',
    label: 'Organic Carbon',
    shortLabel: 'OC',
    unit: '%',
    optimalMin: 1.01,
    optimalMax: 3.0,
  },
  {
    key: 'organicMatter',
    label: 'Organic Matter',
    shortLabel: 'OM',
    unit: '%',
    optimalMin: 2.0,
    optimalMax: 5.0,
  },
  {
    key: 'nitrogen',
    label: 'Nitrogen',
    shortLabel: 'N',
    unit: 'ppm',
    optimalMin: 200,
    optimalMax: 400,
  },
  {
    key: 'phosphorus',
    label: 'Phosphorus',
    shortLabel: 'P',
    unit: 'ppm',
    optimalMin: 10,
    optimalMax: 20,
  },
  {
    key: 'potassium',
    label: 'Potassium',
    shortLabel: 'K',
    unit: 'ppm',
    optimalMin: 120,
    optimalMax: 200,
  },
  {
    key: 'calcium',
    label: 'Calcium',
    shortLabel: 'Ca',
    unit: 'ppm',
    optimalMin: 1000,
    optimalMax: 4500,
  },
  {
    key: 'magnesium',
    label: 'Magnesium',
    shortLabel: 'Mg',
    unit: 'ppm',
    optimalMin: 500,
    optimalMax: 1000,
  },
  {
    key: 'sulfur',
    label: 'Sulfur',
    shortLabel: 'S',
    unit: 'ppm',
    optimalMin: 10,
    optimalMax: 20,
  },
  {
    key: 'iron',
    label: 'Iron',
    shortLabel: 'Fe',
    unit: 'ppm',
    optimalMin: 3.1,
    optimalMax: 5.0,
  },
  {
    key: 'manganese',
    label: 'Manganese',
    shortLabel: 'Mn',
    unit: 'ppm',
    optimalMin: 0.6,
    optimalMax: 1.0,
  },
  {
    key: 'zinc',
    label: 'Zinc',
    shortLabel: 'Zn',
    unit: 'ppm',
    optimalMin: 1.0,
    optimalMax: 1.5,
  },
  {
    key: 'copper',
    label: 'Copper',
    shortLabel: 'Cu',
    unit: 'ppm',
    optimalMin: 0.3,
    optimalMax: 0.5,
  },
  {
    key: 'boron',
    label: 'Boron',
    shortLabel: 'B',
    unit: 'ppm',
    optimalMin: 0,
    optimalMax: 0.5,
  },
];

// Petiole parameter options with optimal ranges for grape cultivation
export const petioleParamOptions: ParamOption[] = [
  {
    key: 'total_nitrogen',
    label: 'Total Nitrogen',
    shortLabel: 'TN',
    unit: '%',
    optimalMin: 1.51,
    optimalMax: 2.21,
  },
  {
    key: 'nitrate_nitrogen',
    label: 'Nitrate N',
    shortLabel: 'NO₃-N',
    unit: 'ppm',
    optimalMin: 700,
    optimalMax: 1000,
  },
  {
    key: 'ammoniacal_nitrogen',
    label: 'Ammonical N',
    shortLabel: 'NH₄-N',
    unit: 'ppm',
    optimalMin: 400,
    optimalMax: 700,
  },
  {
    key: 'phosphorus',
    label: 'Phosphorus',
    shortLabel: 'P',
    unit: '%',
    optimalMin: 0.31,
    optimalMax: 0.51,
  },
  {
    key: 'potassium',
    label: 'Potassium',
    shortLabel: 'K',
    unit: '%',
    optimalMin: 1.51,
    optimalMax: 2.01,
  },
  {
    key: 'calcium',
    label: 'Calcium',
    shortLabel: 'Ca',
    unit: '%',
    optimalMin: 1.51,
    optimalMax: 2.21,
  },
  {
    key: 'magnesium',
    label: 'Magnesium',
    shortLabel: 'Mg',
    unit: '%',
    optimalMin: 0.31,
    optimalMax: 0.61,
  },
  {
    key: 'sulfur',
    label: 'Sulfur',
    shortLabel: 'S',
    unit: '%',
    optimalMin: 0.15,
    optimalMax: 0.51,
  },
  {
    key: 'iron',
    label: 'Iron',
    shortLabel: 'Fe',
    unit: 'ppm',
    optimalMin: 80,
    optimalMax: 120,
  },
  {
    key: 'manganese',
    label: 'Manganese',
    shortLabel: 'Mn',
    unit: 'ppm',
    optimalMin: 40,
    optimalMax: 100,
  },
  {
    key: 'zinc',
    label: 'Zinc',
    shortLabel: 'Zn',
    unit: 'ppm',
    optimalMin: 50,
    optimalMax: 80,
  },
  {
    key: 'copper',
    label: 'Copper',
    shortLabel: 'Cu',
    unit: 'ppm',
    optimalMin: 5,
    optimalMax: 15,
  },
  {
    key: 'boron',
    label: 'Boron',
    shortLabel: 'B',
    unit: 'ppm',
    optimalMin: 25,
    optimalMax: 50,
  },
  {
    key: 'molybdenum',
    label: 'Molybdenum',
    shortLabel: 'Mo',
    unit: 'ppm',
    optimalMin: 0.25,
    optimalMax: 0.51,
  },
  {
    key: 'sodium',
    label: 'Sodium',
    shortLabel: 'Na',
    unit: '%',
    optimalMin: 0.01,
    optimalMax: 0.51,
  },
  {
    key: 'chloride',
    label: 'Chloride',
    shortLabel: 'Cl',
    unit: '%',
    optimalMin: 0.05,
    optimalMax: 0.25,
  },
];
