import type { NutrientCompositionItem, WarehouseItemType, WarehouseUnit } from '@/types';

export interface WarehouseNutrientPreset {
  id: string;
  label: string;
  name: string;
  type: WarehouseItemType;
  unit: WarehouseUnit;
  manufacturer: string;
  default_dose_quantity?: number | null;
  default_dose_unit?: string | null;
  default_dose_basis?: 'total' | 'per_acre' | null;
  composition: NutrientCompositionItem[];
}

function nutrient(nutrient_code: string, percent: number, notes?: string): NutrientCompositionItem {
  return {
    nutrient_code,
    percent,
    basis: 'declared',
    notes: notes ?? null,
  };
}

function npk(n: number, p2o5: number, k2o: number): NutrientCompositionItem[] {
  return [nutrient('N', n), nutrient('P2O5', p2o5), nutrient('K2O', k2o)];
}

export const WAREHOUSE_PRESETS: WarehouseNutrientPreset[] = [
  {
    id: 'mahadhan-smart-24-24-0',
    label: 'Mahadhan SMART 24:24:0',
    name: 'Mahadhan SMART 24:24:0 Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(24, 24, 0),
  },
  {
    id: 'mahadhan-19-19-19',
    label: 'Mahadhan 19:19:19',
    name: 'Mahadhan NutriTech 19:19:19',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [
      { nutrient_code: 'N', percent: 19, basis: 'declared' },
      { nutrient_code: 'P2O5', percent: 19, basis: 'declared' },
      { nutrient_code: 'K2O', percent: 19, basis: 'declared' },
    ],
  },
  {
    id: 'mahadhan-12-61-0',
    label: 'Mahadhan 12:61:00',
    name: 'Mahadhan 12:61:00 Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(12, 61, 0),
  },
  {
    id: 'mahadhan-13-40-13',
    label: 'Mahadhan 13:40:13',
    name: 'Mahadhan 13:40:13 Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(13, 40, 13),
  },
  {
    id: 'mahadhan-0-52-34',
    label: 'Mahadhan 00:52:34',
    name: 'Mahadhan 00:52:34 Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(0, 52, 34),
  },
  {
    id: 'mahadhan-13-0-45',
    label: 'Mahadhan 13:00:45',
    name: 'Mahadhan 13:00:45 Fertiliser (KNO3)',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(13, 0, 45),
  },
  {
    id: 'mahadhan-0-0-50-17-5s',
    label: 'Mahadhan 00:00:50 + 17.5 S',
    name: 'Mahadhan 00:00:50 + 17.5 S (Potassium Sulphate)',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('K2O', 50), nutrient('S', 17.5)],
  },
  {
    id: 'mahadhan-16-16-16',
    label: 'Mahadhan 16:16:16',
    name: 'Mahadhan 16:16:16 Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(16, 16, 16),
  },
  {
    id: 'mahadhan-power-24-24-0',
    label: 'Mahadhan Power 24:24:0',
    name: 'Mahadhan Power 24:24:0',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(24, 24, 0),
  },
  {
    id: 'mahadhan-dap-18-46-0',
    label: 'Mahadhan DAP 18:46:00',
    name: 'Mahadhan DAP Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('N', 18), nutrient('P2O5', 46)],
  },
  {
    id: 'mahadhan-ammonium-sulphate',
    label: 'Mahadhan Ammonium Sulphate',
    name: 'Mahadhan Ammonium Sulphate Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('N', 20.5), nutrient('S', 23)],
  },
  {
    id: 'mahadhan-ssp',
    label: 'Mahadhan SSP',
    name: 'Mahadhan SSP Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('P2O5', 16), nutrient('S', 11), nutrient('Ca', 21)],
  },
  {
    id: 'mahadhan-zinksulf-21',
    label: 'Mahadhan Zinksulf 21%',
    name: 'Mahadhan Zinksulf 21%',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('Zn', 21)],
  },
  {
    id: 'mahadhan-zinksulf-33',
    label: 'Mahadhan Zinksulf 33%',
    name: 'Mahadhan Zinksulf 33%',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('Zn', 33)],
  },
  {
    id: 'mahadhan-bensulf',
    label: 'Mahadhan Bensulf 90% S',
    name: 'Mahadhan Bensulf Superfast',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('S', 90, 'Website description states 90% sulfur + 10% bentonite')],
  },
  {
    id: 'mahadhan-premium-sop',
    label: 'Mahadhan Premium SOP',
    name: 'Mahadhan Premium SOP',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [nutrient('K2O', 50), nutrient('S', 17.5)],
  },
  {
    id: 'mahadhan-premium-mkp',
    label: 'Mahadhan Premium MKP',
    name: 'Mahadhan Premium MKP',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(0, 52, 34),
  },
  {
    id: 'mahadhan-premium-map',
    label: 'Mahadhan Premium MAP',
    name: 'Mahadhan Premium MAP',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(12, 61, 0),
  },
  {
    id: 'mahadhan-premium-kno3',
    label: 'Mahadhan Premium KNO3',
    name: 'Mahadhan Premium KNO3',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: npk(13, 0, 45),
  },
  {
    id: 'mahadhan-potassium-schoenite',
    label: 'Mahadhan Potassium Schoenite',
    name: 'Potassium Schoenite Fertiliser',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Deepak Fertilisers (Mahadhan)',
    composition: [
      nutrient('K2O', 23),
      nutrient('MgO', 90, 'Website copy currently states 90% magnesium oxide'),
    ],
  },
  {
    id: 'vanita-19-19-19',
    label: 'Vanita 19:19:19',
    name: 'Vanita Aditya N:P:K 19:19:19',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(19, 19, 19),
  },
  {
    id: 'vanita-aditya-20-20-20',
    label: 'Vanita 20:20:20',
    name: 'Vanita Aditya N:P:K 20:20:20',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(20, 20, 20),
  },
  {
    id: 'vanita-aditya-13-40-13',
    label: 'Vanita 13:40:13',
    name: 'Vanita Aditya N:P:K 13:40:13',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(13, 40, 13),
  },
  {
    id: 'vanita-aditya-13-0-45',
    label: 'Vanita 13:00:45',
    name: 'Vanita Aditya N:P:K 13:00:45',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(13, 0, 45),
  },
  {
    id: 'vanita-aditya-12-61-0',
    label: 'Vanita 12:61:00',
    name: 'Vanita Aditya N:P:K 12:61:00',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(12, 61, 0),
  },
  {
    id: 'vanita-aditya-0-52-34',
    label: 'Vanita 00:52:34',
    name: 'Vanita Aditya N:P:K 00:52:34',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(0, 52, 34),
  },
  {
    id: 'vanita-aditya-0-0-50',
    label: 'Vanita 00:00:50 (SOP)',
    name: 'Vanita Aditya N:P:K 00:00:50 (SOP)',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(0, 0, 50),
  },
  {
    id: 'vanita-aditya-16-8-24',
    label: 'Vanita 16:08:24',
    name: 'Vanita Aditya N:P:K 16:08:24',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(16, 8, 24),
  },
  {
    id: 'vanita-aditya-13-5-26',
    label: 'Vanita 13:05:26',
    name: 'Vanita Aditya N:P:K 13:05:26',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(13, 5, 26),
  },
  {
    id: 'vanita-aditya-0-60-20',
    label: 'Vanita 00:60:20',
    name: 'Vanita Aditya N:P:K 00:60:20',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(0, 60, 20),
  },
  {
    id: 'vanita-aditya-0-58-18',
    label: 'Vanita 00:58:18',
    name: 'Vanita Aditya N:P:K 00:58:18',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: npk(0, 58, 18),
  },
  {
    id: 'vanita-nobel-ca-10-0-20-7',
    label: 'Vanita Nobel-Ca 10:00:20:07',
    name: 'Vanita Nobel-Ca N:P:K:Ca 10:00:20:07',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: [nutrient('N', 10), nutrient('P2O5', 0), nutrient('K2O', 20), nutrient('Ca', 7)],
  },
  {
    id: 'vanita-nobel-fe-10-30-0-2',
    label: 'Vanita Nobel-Fe 10:30:00:02',
    name: 'Vanita Nobel-Fe N:P:K:Fe 10:30:00:02',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: [nutrient('N', 10), nutrient('P2O5', 30), nutrient('K2O', 0), nutrient('Fe', 2)],
  },
  {
    id: 'vanita-nobel-mgo-0-54-17-6',
    label: 'Vanita Nobel-MgO 00:54:17:06',
    name: 'Vanita Nobel-MgO N:P:K:MgO 00:54:17:06',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: [nutrient('N', 0), nutrient('P2O5', 54), nutrient('K2O', 17), nutrient('MgO', 6)],
  },
  {
    id: 'vanita-en-rich-21',
    label: 'Vanita En-Rich 21:05:00:17',
    name: 'Vanita En-Rich 21 N:P:K:S 21:05:00:17',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: [nutrient('N', 21), nutrient('P2O5', 5), nutrient('K2O', 0), nutrient('S', 17)],
  },
  {
    id: 'vanita-tanbor-14-5-17-0-2-to-0-3',
    label: 'Vanita Tanbor 14.5:17.0:0.2-0.3',
    name: 'Vanita Tanbor N:Ca:B 14.5:17.0:0.2-0.3',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: [
      nutrient('N', 14.5),
      nutrient('Ca', 17),
      nutrient('B', 0.25, 'Label range: 0.2-0.3'),
    ],
  },
  {
    id: 'vanita-potassium-magnesium-sulphate',
    label: 'Vanita K2O 22, MgO 18, S 20',
    name: 'Vanita Potassium Magnesium Sulphate',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Vanita Agro',
    composition: [nutrient('K2O', 22), nutrient('MgO', 18), nutrient('S', 20)],
  },
  {
    id: 'yara-19-19-19',
    label: 'YaraTera 19:19:19',
    name: 'YaraTera Deltaspray 19:19:19',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: npk(19, 19, 19),
  },
  {
    id: 'yara-13-0-45',
    label: 'YaraTera 13:00:45',
    name: 'YaraTera Krista K Plus 13:00:45',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: npk(13, 0, 45),
  },
  {
    id: 'yara-12-61-0',
    label: 'YaraTera 12:61:00',
    name: 'YaraTera Krista MAP 12:61:00',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: npk(12, 61, 0),
  },
  {
    id: 'yara-0-52-34',
    label: 'YaraTera 00:52:34',
    name: 'YaraTera Krista MKP 00:52:34',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: npk(0, 52, 34),
  },
  {
    id: 'yara-0-0-50',
    label: 'YaraTera 00:00:50',
    name: 'YaraTera Krista SOP 00:00:50',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: [nutrient('K2O', 50), nutrient('S', 17.5)],
  },
  {
    id: 'yara-calcinit',
    label: 'YaraTera Calcinit',
    name: 'YaraTera Calcinit (Calcium Nitrate)',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: [nutrient('N', 15.5), nutrient('Ca', 19)],
  },
  {
    id: 'yara-urea',
    label: 'Yara Urea 46% N',
    name: 'Yara Urea',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Yara India',
    composition: [nutrient('N', 46)],
  },
  {
    id: 'npk-12-61-0',
    label: '12:61:00 MAP',
    name: 'Mono Ammonium Phosphate 12:61:00',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Generic FCO Grade',
    composition: [
      { nutrient_code: 'N', percent: 12, basis: 'declared' },
      { nutrient_code: 'P2O5', percent: 61, basis: 'declared' },
    ],
  },
  {
    id: 'npk-0-0-50',
    label: '00:00:50 SOP',
    name: 'Sulphate of Potash 00:00:50',
    type: 'fertilizer',
    unit: 'kg',
    manufacturer: 'Generic FCO Grade',
    composition: [
      { nutrient_code: 'K2O', percent: 50, basis: 'declared' },
      { nutrient_code: 'S', percent: 17, basis: 'declared' },
    ],
  },
];

// Backward-compatible alias while call sites migrate to the generic preset name.
export const MAHARASHTRA_WAREHOUSE_PRESETS = WAREHOUSE_PRESETS;
