-- Grape Annexure label-claim schema
-- This migration is intentionally additive/idempotent and safe for pre-apply consolidation.

create extension if not exists moddatetime schema extensions;

-- ============================================================
-- Label claim sources
-- ============================================================
create table if not exists public.chemical_label_sources (
  id bigint generated by default as identity primary key,
  source_type text not null default 'annexure' check (source_type in ('annexure', 'label', 'manual_review', 'other')),
  issuing_body text not null,
  source_document text not null,
  source_title text not null,
  source_url text,
  crop text not null default 'grape',
  revision_date date not null,
  effective_from date,
  effective_to date,
  document_checksum text,
  edition_defaults jsonb not null default '{}'::jsonb,
  review_status text not null default 'pending_review' check (review_status in ('pending_review', 'verified', 'rejected', 'superseded')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists chemical_label_sources_identity_unique
  on public.chemical_label_sources (
    source_type,
    lower(issuing_body),
    lower(source_document),
    lower(crop),
    revision_date
  );

create index if not exists chemical_label_sources_crop_revision_idx
  on public.chemical_label_sources (lower(crop), revision_date, review_status);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chemical_label_sources_effective_from_to_check'
      and conrelid = 'public.chemical_label_sources'::regclass
  ) then
    alter table public.chemical_label_sources
      add constraint chemical_label_sources_effective_from_to_check
      check (
        effective_from is null
        or effective_to is null
        or effective_from <= effective_to
      );
  end if;
end $$;

-- ============================================================
-- Versioned label claims
-- ============================================================
create table if not exists public.chemical_label_claims (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.chemical_label_sources(id) on delete cascade,
  product_id bigint not null references public.chemical_products(id) on delete restrict,
  crop text not null default 'grape',
  source_page int,
  source_serial text not null,
  formulation_name text not null,
  active_ingredient text,
  target_problem text not null,
  dose_value numeric(12,4) not null check (dose_value >= 0),
  dose_unit text not null,
  dose_basis text not null check (dose_basis in ('per_liter_water', 'per_acre', 'total', 'other')),
  phi_min_days int check (phi_min_days >= 0),
  phi_max_days int check (phi_max_days >= 0),
  phi_note text,
  systemic_class text,
  restrictions text,
  resistance_markers text,
  max_applications_per_season int check (max_applications_per_season is null or max_applications_per_season >= 0),
  min_application_interval_days int check (min_application_interval_days is null or min_application_interval_days >= 0),
  max_application_interval_days int check (max_application_interval_days is null or max_application_interval_days >= 0),
  application_interval_note text,
  stage_restrictions text,
  review_status text not null default 'pending_review' check (review_status in ('pending_review', 'verified', 'rejected', 'superseded')),
  effective_from date,
  effective_to date,
  supersedes_claim_id bigint references public.chemical_label_claims(id) on delete set null,
  is_active boolean not null default true,
  review_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists chemical_label_claims_source_identity_unique
  on public.chemical_label_claims (source_id, lower(source_serial), lower(target_problem));

create index if not exists chemical_label_claims_product_idx
  on public.chemical_label_claims (product_id, lower(crop), review_status, is_active);

create index if not exists chemical_label_claims_target_idx
  on public.chemical_label_claims (lower(crop), lower(target_problem), review_status, is_active);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chemical_label_claims_phi_days_order_check'
      and conrelid = 'public.chemical_label_claims'::regclass
  ) then
    alter table public.chemical_label_claims
      add constraint chemical_label_claims_phi_days_order_check
      check (
        phi_min_days is null
        or phi_max_days is null
        or phi_min_days <= phi_max_days
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'chemical_label_claims_interval_order_check'
      and conrelid = 'public.chemical_label_claims'::regclass
  ) then
    alter table public.chemical_label_claims
      add constraint chemical_label_claims_interval_order_check
      check (
        min_application_interval_days is null
        or max_application_interval_days is null
        or min_application_interval_days <= max_application_interval_days
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'chemical_label_claims_effective_from_to_check'
      and conrelid = 'public.chemical_label_claims'::regclass
  ) then
    alter table public.chemical_label_claims
      add constraint chemical_label_claims_effective_from_to_check
      check (
        effective_from is null
        or effective_to is null
        or effective_from <= effective_to
      );
  end if;
end $$;

-- ============================================================
-- Claim MRLs
-- ============================================================
create table if not exists public.chemical_label_claim_mrls (
  id bigint generated by default as identity primary key,
  claim_id bigint not null references public.chemical_label_claims(id) on delete cascade,
  market text not null,
  residue_name text not null,
  mrl_value numeric(12,4) check (mrl_value is null or mrl_value >= 0),
  mrl_unit text not null default 'mg/kg',
  no_mrl_required boolean not null default false,
  source_note text,
  created_at timestamptz not null default now()
);

create unique index if not exists chemical_label_claim_mrls_identity_unique
  on public.chemical_label_claim_mrls (claim_id, lower(market), lower(residue_name));

create index if not exists chemical_label_claim_mrls_claim_idx
  on public.chemical_label_claim_mrls (claim_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chemical_label_claim_mrls_value_or_exemption_check'
      and conrelid = 'public.chemical_label_claim_mrls'::regclass
  ) then
    alter table public.chemical_label_claim_mrls
      add constraint chemical_label_claim_mrls_value_or_exemption_check
      check (
        no_mrl_required = true
        or mrl_value is not null
      );
  end if;
end $$;

-- ============================================================
-- Existing table extensions
-- ============================================================
alter table if exists public.chemical_mix_components
  add column if not exists label_claim_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chemical_mix_components_label_claim_fk'
      and conrelid = 'public.chemical_mix_components'::regclass
  ) then
    alter table public.chemical_mix_components
      add constraint chemical_mix_components_label_claim_fk
      foreign key (label_claim_id)
      references public.chemical_label_claims(id)
      on delete set null;
  end if;
end $$;

create index if not exists chemical_mix_components_label_claim_idx
  on public.chemical_mix_components (label_claim_id);

do $$
begin
  if exists (
    select 1
    from public.chemical_mixes
    group by lower(crop), lower(name), coalesce(lower(target_problem), '')
    having count(*) > 1
  ) then
    raise exception 'chemical_mixes contains duplicate crop/name/target_problem rows; aborting unique-index swap';
  end if;
end $$;

drop index if exists public.chemical_mixes_crop_name_unique;

create unique index if not exists chemical_mixes_crop_name_target_problem_unique
  on public.chemical_mixes (lower(crop), lower(name), coalesce(lower(target_problem), ''));

alter table if exists public.spray_records
  add column if not exists compliance_status text,
  add column if not exists compliance_snapshot jsonb;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'spray_records_compliance_status_check'
      and conrelid = 'public.spray_records'::regclass
  ) then
    alter table public.spray_records
      add constraint spray_records_compliance_status_check
      check (compliance_status in ('allowed', 'warning', 'blocked', 'unverified'));
  end if;
end $$;

create index if not exists spray_records_compliance_status_idx
  on public.spray_records (farm_id, season_id, compliance_status);

-- Catalog security model:
-- This migration enables row-level security and creates read-only SELECT policies
-- for the authenticated role on the catalog tables below. Writes should use
-- service-role credentials (seeding/migrations/admin operations).

-- ============================================================
-- Catalog RLS (authenticated read-only)
-- ============================================================
do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'chemical_label_sources',
    'chemical_label_claims',
    'chemical_label_claim_mrls'
  ]
  loop
    execute format('alter table public.%I enable row level security', tbl);

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = tbl
        and policyname = 'Allow authenticated read access'
    ) then
      execute format(
        'create policy "Allow authenticated read access" on public.%I for select to authenticated using (true)',
        tbl
      );
    end if;
  end loop;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'handle_chemical_label_sources_updated_at'
  ) then
    create trigger handle_chemical_label_sources_updated_at
      before update on public.chemical_label_sources
      for each row execute procedure extensions.moddatetime(updated_at);
  end if;

  if not exists (
    select 1 from pg_trigger where tgname = 'handle_chemical_label_claims_updated_at'
  ) then
    create trigger handle_chemical_label_claims_updated_at
      before update on public.chemical_label_claims
      for each row execute procedure extensions.moddatetime(updated_at);
  end if;
end $$;
