-- Unified PHI + Maharashtra master catalog schema
-- This migration is intentionally additive/idempotent and safe for pre-apply consolidation.

-- ============================================================
-- Core catalog: products
-- ============================================================
create table if not exists public.chemical_products (
  id bigint generated by default as identity primary key,
  name text not null,
  manufacturer text,
  active_ingredient text,
  input_type text not null default 'other' check (input_type in ('spray', 'fertilizer', 'biostimulant', 'adjuvant', 'other')),
  verification_tier text not null default 'provisional' check (verification_tier in ('verified', 'provisional')),
  formulation text,
  state_code text not null default 'MH',
  source_reference text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists chemical_products_state_name_unique
  on public.chemical_products (state_code, lower(name));

create index if not exists chemical_products_input_type_idx
  on public.chemical_products (input_type, verification_tier, is_active);

create index if not exists chemical_products_name_search_idx
  on public.chemical_products (lower(name));

-- ============================================================
-- Product aliases
-- ============================================================
create table if not exists public.chemical_product_aliases (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.chemical_products(id) on delete cascade,
  alias text not null,
  locale text not null default 'en',
  alias_kind text not null default 'trade' check (alias_kind in ('trade', 'ocr', 'common', 'legacy')),
  source text,
  created_at timestamptz not null default now()
);

create unique index if not exists chemical_product_aliases_unique
  on public.chemical_product_aliases (product_id, locale, lower(alias));

create index if not exists chemical_product_aliases_alias_idx
  on public.chemical_product_aliases (lower(alias));

-- ============================================================
-- Product compositions
-- ============================================================
create table if not exists public.chemical_product_compositions (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.chemical_products(id) on delete cascade,
  component_code text not null,
  component_type text not null check (component_type in ('nutrient', 'active_ingredient', 'other')),
  percent numeric(8,4) not null check (percent >= 0 and percent <= 100),
  basis text not null default 'declared',
  verified boolean not null default false,
  source_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists chemical_product_compositions_unique
  on public.chemical_product_compositions (product_id, lower(component_code), basis);

-- ============================================================
-- Mix definitions
-- ============================================================
create table if not exists public.chemical_mixes (
  id bigint generated by default as identity primary key,
  name text not null,
  target_problem text,
  application_mode text check (application_mode in ('preventive', 'curative', 'both', 'unspecified')),
  source_page int,
  source_document text,
  crop text not null default 'grape',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists chemical_mixes_crop_name_unique
  on public.chemical_mixes (lower(crop), lower(name));

create table if not exists public.chemical_mix_components (
  id bigint generated by default as identity primary key,
  mix_id bigint not null references public.chemical_mixes(id) on delete cascade,
  product_id bigint not null references public.chemical_products(id) on delete restrict,
  sequence_no int not null default 1,
  dose_value numeric(12,4) not null,
  dose_unit text not null check (dose_unit in ('gm', 'ml')),
  dose_basis text not null check (dose_basis in ('per_liter', 'per_100_liter', 'fixed_per_tank')),
  base_tank_liters numeric(12,2),
  product_name_snapshot text,
  active_ingredient_snapshot text,
  notes text,
  created_at timestamptz not null default now()
);

create unique index if not exists chemical_mix_components_unique_seq
  on public.chemical_mix_components (mix_id, sequence_no);

create index if not exists chemical_mix_components_mix_idx
  on public.chemical_mix_components (mix_id);

create index if not exists chemical_mix_components_product_idx
  on public.chemical_mix_components (product_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'check_fixed_tank_requires_base'
      and conrelid = 'public.chemical_mix_components'::regclass
  ) then
    alter table public.chemical_mix_components
      add constraint check_fixed_tank_requires_base
      check (
        dose_basis <> 'fixed_per_tank'
        or (base_tank_liters is not null and base_tank_liters > 0)
      );
  end if;
end $$;

-- ============================================================
-- PHI rules
-- ============================================================
create table if not exists public.chemical_phi_rules (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.chemical_products(id) on delete cascade,
  crop text not null,
  phi_days int not null check (phi_days >= 0),
  evidence_level text,
  source_note text,
  source_url text,
  verified boolean not null default false,
  effective_from date,
  effective_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists chemical_phi_rules_unique_active
  on public.chemical_phi_rules (product_id, lower(crop), coalesce(effective_from, date '1900-01-01'));

create index if not exists chemical_phi_rules_verified_idx
  on public.chemical_phi_rules (product_id, lower(crop), verified);

-- ============================================================
-- Existing table extensions
-- ============================================================
alter table if exists public.farm_seasons
  add column if not exists target_harvest_date date;

alter table if exists public.spray_records
  add column if not exists catalog_mix_id bigint references public.chemical_mixes(id) on delete set null,
  add column if not exists governing_phi_days int,
  add column if not exists safe_harvest_date date,
  add column if not exists phi_calc_version text,
  add column if not exists phi_blocking_component text,
  add column if not exists phi_status text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'spray_records_phi_status_check'
      and conrelid = 'public.spray_records'::regclass
  ) then
    alter table public.spray_records
      add constraint spray_records_phi_status_check
      check (phi_status in ('verified', 'legacy_unverified', 'unknown'));
  end if;
end $$;

alter table if exists public.warehouse_items
  add column if not exists catalog_product_id bigint references public.chemical_products(id) on delete set null,
  add column if not exists catalog_mapping_status text,
  add column if not exists catalog_mapping_source text,
  add column if not exists catalog_mapped_at timestamptz;

alter table if exists public.warehouse_items
  alter column catalog_mapping_status set default 'unmapped',
  alter column catalog_mapping_source set default 'manual';

update public.warehouse_items
set catalog_mapping_status = coalesce(catalog_mapping_status, 'unmapped')
where catalog_mapping_status is null;

update public.warehouse_items
set catalog_mapping_source = coalesce(catalog_mapping_source, 'manual')
where catalog_mapping_source is null;

alter table if exists public.warehouse_items
  alter column catalog_mapping_status set not null,
  alter column catalog_mapping_source set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'warehouse_items_catalog_mapping_status_check'
      and conrelid = 'public.warehouse_items'::regclass
  ) then
    alter table public.warehouse_items
      add constraint warehouse_items_catalog_mapping_status_check
      check (catalog_mapping_status in ('mapped_verified', 'mapped_provisional', 'unmapped'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'warehouse_items_catalog_mapping_source_check'
      and conrelid = 'public.warehouse_items'::regclass
  ) then
    alter table public.warehouse_items
      add constraint warehouse_items_catalog_mapping_source_check
      check (catalog_mapping_source in ('manual', 'preset', 'auto'));
  end if;
end $$;

-- ============================================================
-- Additional indexes
-- ============================================================
create index if not exists farm_seasons_farm_end_idx
  on public.farm_seasons (farm_id, end_date);

create index if not exists spray_records_phi_lookup_idx
  on public.spray_records (farm_id, season_id, date, safe_harvest_date);

create index if not exists warehouse_items_catalog_product_idx
  on public.warehouse_items (catalog_product_id);

create index if not exists warehouse_items_mapping_status_idx
  on public.warehouse_items (catalog_mapping_status, type);

-- Security model note:
-- This migration does not change RLS/grants. Keep catalog table access aligned with
-- the project's existing database security standard (RLS or grants).

-- ============================================================
-- Catalog RLS (authenticated read-only)
-- ============================================================
do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'chemical_products',
    'chemical_product_aliases',
    'chemical_product_compositions',
    'chemical_mixes',
    'chemical_mix_components',
    'chemical_phi_rules'
  ]
  loop
    execute format('alter table public.%I enable row level security', tbl);

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = tbl
        and policyname = 'Allow authenticated read access'
    ) then
      execute format(
        'create policy "Allow authenticated read access" on public.%I for select to authenticated using (true)',
        tbl
      );
    end if;
  end loop;
end $$;
