-- Close inherited API access while retaining explicit app RPC grants.
-- Backend jobs keep service_role access; trigger invocation does not require caller EXECUTE.
SET lock_timeout = '5s';

REVOKE EXECUTE ON FUNCTION public.accept_organization_invite(uuid,uuid,uuid,text,text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.accept_organization_invite(uuid,uuid,uuid,text,text,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.assert_organization_client_assignee_is_agronomist() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assert_organization_client_assignee_is_agronomist() TO service_role;
REVOKE EXECUTE ON FUNCTION public.assistant_delete_user_data(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.assistant_export_user_data(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.assistant_purge_expired_data() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assistant_purge_expired_data() TO service_role;
REVOKE EXECUTE ON FUNCTION public.begin_farm_setup_reminder_dispatch(uuid,uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.begin_farm_setup_reminder_dispatch(uuid,uuid[]) TO service_role;
REVOKE EXECUTE ON FUNCTION public.bootstrap_farm_seasons_and_assignments() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.bootstrap_farm_seasons_and_assignments() TO service_role;
REVOKE EXECUTE ON FUNCTION public.can_access_org_client(uuid,uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_access_org_client_from_farm_owner(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_create_delegated_log(uuid,uuid,bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.claim_due_farm_setup_reminders(uuid,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_due_farm_setup_reminders(uuid,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.claim_invite_account_has_password(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.complete_farm_setup_reminder_on_farm_insert() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_farm_setup_reminder_on_farm_insert() TO service_role;
REVOKE EXECUTE ON FUNCTION public.confirm_settlement_atomic(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_delegated_log(uuid,uuid,bigint,text,date,jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_triage_from_petiole_test() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_triage_from_petiole_test() TO service_role;
REVOKE EXECUTE ON FUNCTION public.create_visit_with_followups(uuid,bigint,date,text,jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.decay_context_relevance() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.decay_context_relevance() TO service_role;
REVOKE EXECUTE ON FUNCTION public.delete_delegated_log(text,bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.end_farm_season(bigint,date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.expire_old_task_recommendations() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.expire_old_task_recommendations() TO service_role;
REVOKE EXECUTE ON FUNCTION public.finish_farm_setup_reminder_claim(uuid,uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.finish_farm_setup_reminder_claim(uuid,uuid[]) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_challenges_remaining_count() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_challenges_remaining_count() TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_delegated_farm_activity(uuid,uuid,bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_farmer_recommendations(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_next_available_challenge() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_next_available_challenge() TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_org_followup_adherence() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_org_latest_petiole() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_professional_workspace() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
REVOKE EXECUTE ON FUNCTION public.initialize_farm_setup_reminder() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_farm_setup_reminder() TO service_role;
REVOKE EXECUTE ON FUNCTION public.is_org_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_org_member(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.join_organization_by_slug(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mark_challenge_as_used(uuid,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mark_challenge_as_used(uuid,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.notify_fertilizer_plan_created() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.notify_fertilizer_plan_created() TO service_role;
REVOKE EXECUTE ON FUNCTION public.phone_in_use(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.recompute_farm_season_assignments(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.remove_organization_member(uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.remove_organization_member(uuid,uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.reorder_farms(integer[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rls_auto_enable() TO service_role;
REVOKE EXECUTE ON FUNCTION public.send_fertilizer_plan(uuid,text,jsonb,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_client_payment_status(uuid,boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO service_role;
REVOKE EXECUTE ON FUNCTION public.set_updated_at_timestamp() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_updated_at_timestamp() TO service_role;
REVOKE EXECUTE ON FUNCTION public.stamp_fertilizer_plan_farm_area() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.stamp_fertilizer_plan_farm_area() TO service_role;
REVOKE EXECUTE ON FUNCTION public.start_farm_season(bigint,date,text,jsonb,text,text,integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.touch_updated_at() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_ai_conversation_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_ai_conversation_updated_at() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_delegated_log(text,bigint,jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_farmer_ai_profile_timestamp() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_farmer_ai_profile_timestamp() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_fertilizer_plan(uuid,text,text,jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_prompt_likes_count() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_prompt_likes_count() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_tag_usage_count() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_tag_usage_count() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_task_reminders_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_task_reminders_updated_at() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_updated_at_column() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_warehouse_items_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_warehouse_items_updated_at() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_worker_advance_balance() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_worker_advance_balance() TO service_role;
REVOKE EXECUTE ON FUNCTION public.update_worker_settlements_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_worker_settlements_updated_at() TO service_role;
REVOKE EXECUTE ON FUNCTION public.upsert_user_guided_tour_state(text,text,text,integer,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone,bigint,text,integer,boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validate_consultant_visit_consistency() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_consultant_visit_consistency() TO service_role;
REVOKE EXECUTE ON FUNCTION public.validate_petiole_triage_consistency() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_petiole_triage_consistency() TO service_role;
REVOKE EXECUTE ON FUNCTION public.validate_task_linked_record() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_task_linked_record() TO service_role;
REVOKE EXECUTE ON FUNCTION public.validate_visit_followup_consistency() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_visit_followup_consistency() TO service_role;

-- Match the intended service-only access in the reminder campaign migration.
REVOKE EXECUTE ON FUNCTION public.farm_setup_local_send_at(timestamptz, text, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.farm_setup_local_send_at(timestamptz, text, integer) TO service_role;

-- pg_catalog resolves built-ins first; pg_temp must never shadow application tables.
-- public and extensions do not grant CREATE to API roles.
ALTER FUNCTION public.accept_organization_invite(uuid,uuid,uuid,text,text,text) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.assert_organization_client_assignee_is_agronomist() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.assistant_delete_user_data(uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.assistant_export_user_data(uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.assistant_purge_expired_data() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.bootstrap_farm_seasons_and_assignments() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.can_access_org_client(uuid,uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.can_access_org_client_from_farm_owner(uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.can_create_delegated_log(uuid,uuid,bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.confirm_settlement_atomic(bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.create_delegated_log(uuid,uuid,bigint,text,date,jsonb) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.create_triage_from_petiole_test() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.create_visit_with_followups(uuid,bigint,date,text,jsonb) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.decay_context_relevance() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.delete_delegated_log(text,bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.end_farm_season(bigint,date) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.expire_old_task_recommendations() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_challenges_remaining_count() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_delegated_farm_activity(uuid,uuid,bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_farmer_recommendations(bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_next_available_challenge() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_org_followup_adherence() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_org_latest_petiole() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.get_professional_workspace() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.handle_new_user() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.insert_fertilizer_plan_items(uuid,jsonb) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.is_org_admin(uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.is_org_member(uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.join_organization_by_slug(text) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.mark_challenge_as_used(uuid,text) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.match_agronomy_chunks(vector,integer,text) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.match_assistant_memories(vector,integer,uuid,bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.phone_in_use(text) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.recompute_farm_season_assignments(bigint) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.remove_organization_member(uuid,uuid) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.reorder_farms(integer[]) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.send_fertilizer_plan(uuid,text,jsonb,text) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.set_client_payment_status(uuid,boolean) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.set_updated_at() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.set_updated_at_timestamp() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.stamp_fertilizer_plan_farm_area() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.start_farm_season(bigint,date,text,jsonb,text,text,integer) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.touch_updated_at() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_ai_conversation_updated_at() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_delegated_log(text,bigint,jsonb) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_farmer_ai_profile_timestamp() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_fertilizer_plan(uuid,text,text,jsonb) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_prompt_likes_count() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_tag_usage_count() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_task_reminders_updated_at() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_updated_at_column() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_warehouse_items_updated_at() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_worker_advance_balance() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.update_worker_settlements_updated_at() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.upsert_user_guided_tour_state(text,text,text,integer,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone,bigint,text,integer,boolean) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.validate_consultant_visit_consistency() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.validate_fertilizer_plan_items(jsonb) SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.validate_petiole_triage_consistency() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.validate_task_linked_record() SET search_path = pg_catalog, public, extensions, pg_temp;
ALTER FUNCTION public.validate_visit_followup_consistency() SET search_path = pg_catalog, public, extensions, pg_temp;

ALTER FUNCTION public.notify_fertilizer_plan_created() SET search_path = pg_catalog, public, extensions, vault, pg_temp;

-- New postgres-owned functions require deliberate API grants.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated;
